### ISSUE TITLE
[BUG] Dates on zipped files are off by decades

### ISSUE THREAD

**Issue by morula** [Touffy/client-zip#54]
**Describe the bug**
Special characters (äöüè ...) in the file name are not displayed correctly with Windows Explorer. Even if the file is unzipped by the Windows own tool the filename is not displayed correctly. However, unpacking by 7zip works correctly.

If the ZIP file is created with JSZIP, the file names are displayed correctly with the Windows tools.

Example:
- expected filename: äöüè___milano.gif
- displayed filename: ├ñ├Â├╝├¿___milano.gif

**To Reproduce**
```import { downloadZip } from "https://cdn.jsdelivr.net/npm/client-zip/index.js"

async function downloadTestZip() {
  // define what we want in the ZIP
  const intro = { name: "äöüè_milano.txt", lastModified: new Date(), input: "Hello. This is the client-zip library." }

  // get the ZIP stream in a Blob
  const blob = await downloadZip([intro]).blob()

  // make and click a temporary link to download the Blob
  const link = document.createElement("a")
  link.href = URL.createObjectURL(blob)
  link.download = "test.zip"
  link.click()
  link.remove()

  // in real life, don't forget to revoke your Blob URLs if you use them
}
```

**Expected behavior**
The filename should be created with the same character set as with the other tools (example JSZIP).

**Desktop (please complete the following information):**
 - Windows 11
 - Browser: Chrome Version 109.0.5414.75 (Official Build) (32-bit)

**Comment by Touffy** [comment]
Hello. This sounds like the previously reported problem in #23 . Please read the conversation there and if necessary, reopen that issue. Basically, it *may* be solved by using the Unicode Path attribute, or not… we're not sure because nobody has tested it so far, as nobody felt like it was worth trying. What we do know for sure, is that it won't be solved by using "the same character set" as the host OS, because we actually don't know what it is (Windows can use a variety of encodings and doesn't tell JavaScript which one it is).

**Comment by Touffy** [comment]
The EFS bit added in the latest release may have solved your issue with less hassle than the Unicode extra field. Can you confirm ?
