### ISSUE TITLE
[FEATURE] Support parallel downloading

### ISSUE THREAD

**Issue by cprussin** [Touffy/client-zip#57]
**Is your feature request related to a problem? Please describe.**
Not really a problem, more just a potential performance improvement

**Why is your feature relevant to client-zip?**
`client-zip` currently is not very amenable to doing parallel downloads for the files going into the zip.  But parallellizing or batching the downloads can result in pretty significant improvements on the total download speed.  You can try tricking it by doing something along these lines:

```ts
const mkFile = async (input: SomeType): Promise<InputWithoutMeta> => { ... };
...
downloadZip(activate(inputs));
...
async function* activate(inputs: SomeType[]) {
  const rest = await Promise.all(inputs.map(input => mkFile(input))); // or do this in batches instead
  for (const file of rest) {
    yield file;
  }
}
```

But that will cause the response to not come back to the browser until after all the files (or at least the first batch) are downloaded, so so it's a bad experience and it effectively breaks streaming.

So instead, something like this works:

```ts
downloadZip(raceAll(inputs.map(input => mkFile(input))));

async function* raceAll<T>(promises: Promise<T>[]): AsyncGenerator<T> {
  const wrappedPromises: Promise<T>[] = [];
  const resolvers: ((input: Promise<T>) => void)[] = [];

  for (const promise of promises) {
    wrappedPromises.push(new Promise(resolve => resolvers.push(resolve)));
    promise.finally(() => (resolvers.shift() as (input: Promise<T>) => void)(promise));
  }

  for (const promise of wrappedPromises) {
    yield await promise;
  }
}
```

(credit to https://stackoverflow.com/questions/70044213/async-generator-yielding-promise-results-as-they-are-resolved for helping me put together `raceAll`)

But there are some issues -- for one, this will still wait for the first file to be completed before initiating the file selection in the browser, which isn't a great experience and could be a really slow wait, depending on how slow the files are to download.  For two, it's simply ugly and complicated for what seems like it would be a pretty common use case, and it's not exactly straightforward to write a `raceAll` generator that does the right thing (although I feel sure there are some libraries somewhere that have that function)

**Describe the solution you'd like**
I think the solution here would split into two separate changes:

1. Find a way to trigger the download to start _before_ the first file download completes.  I'm not familiar enough with the `ReadableStream` apis to know how / if this is possible, but maybe it would be possible to enqueue an empty chunk to the controller in the `start` callback to the stream?  Or maybe a fix here involves setting some magic combination of headers onto the `Response`, but I'm not sure if the response is even being received by the browser before the first file comes back (I haven't figured out how to see the responses from a service worker in web inspector yet).  I would need to play with it a bit more to know what's possible here as it's a bit out of my expertise, but I am guessing there's some way to get the stream to be seen as opened by the browser even though no data has yet been received.
2. Expose some nicer apis for doing things in batches.  Ideas here that may help could be e.g. bundling `raceAll` and wrapping it in something like `downloadZipBatch: (inputs: Promise<InputWithoutMeta>[], batchSize: number) => Response`.

**Describe alternatives you've considered**
see above

**Comment by Touffy** [comment]
The way I see it, `downloadZip` has no good reason to consume more than one input at a time. The ZIP output can only be created sequentially, and doing CRC32s in parallel Workers would force us to buffer entire files in memory.

On the other hand, you want to always have an input ready for `downloadZip` as soon as it needs one. That's a noble goal, but "not my problem".

If I imagine your situation accurately, you have many small files on a high-latency host and, using a simple generator as shown in my example, you `fetch` each file in sequence only when the previous file has been yielded. If the previous file was small, `downloadZip` will have finished processing it faster than `fetch` can resolve a Response for the next one, so `downloadZip` will have to sit idle until the source generator yields again.

Obviously, the bottleneck in that situation is not `downloadZip` but the source generator, and the solution is to add an output buffer to that generator (possibly by rewriting it as a ReadableStream) so it can keep fetching more files (up to a reasonable high water mark, which, given Web browser's typical limitations, should be somewhere between 3 and 6).

Does that sound good ? and of course, if you write something like that before I do, I would gladly include it in the examples.

**Comment by cprussin** [comment]
@Touffy makes sense to me!  To be clear, are you saying that you believe any common abstractions that would need to live in any consumer's code who wants to do something like this should live outside the library (although possibly with some examples showing how to do it)?  As in, you wouldn't want to expose some APIs within the library that implement eronomic improvements like this but that aren't actually part of zipping directly?

Either way, I ended up going another route here so this is no longer something I need to invest time into right now -- but I do think it would be nice to contribute something back so I will try to get to it at some point and post a PR back, either with an example or with a library function that implements such an abstraction, whichever you prefer.

**Comment by Touffy** [comment]
Yes, you understood me correctly.

I'm sure your use case is quite common and it would be useful to create a library that takes, say, an iterable of Requests, and outputs a buffered stream of Responses that `downloadZip` can consume. I just don't think that library should be part of client-zip.

**Comment by Touffy** [comment]
As you can see in the freshly updated benchmarks (experiment 2, Conflux vs everyone else), using a stream to buffer several responses really works !

I'm closing this issue since it's not something that will be done in client-zip itself, but if there isn't already a small implementation of this feature on the Web, I'll publish one sometime.

**Comment by Touffy** [comment]
I have modified my second test (with 6k small files fetched over HTTP) to feed each library from a stream instead of an asyncIterable of Responses. The improvement is fantastic in Safari, and doubtful in Chrome because — in addition to Chrome's usual slowness with Streams — each run takes longer than the last (but the first few runs are still faster than before).

time to zip 6214 small TGA files (total 119 MB) in Safari
--------------
lib |  stream (highWaterMark: 3) |  asyncIterable | speedup
---|----------------------------|---------------|--------
client-zip | 1.657s | 2.173s | 24%
fflate     | 1.645s | 2.157s |  24%
Zip.js     | 1.892s | 3.158s | 40%
Conflux    | 1.548s | 1.794s | 14%
JSZIP      | 2.159s | 2.631s | 18%

(Zip.js might have fixed some performance issues since my last round of tests, I saw there were a bunch of patches in the last few days)

**Comment by sntran** [comment]
I don't fully understand Zip specs, but can we allocate the inputs ahead of time in the zipped response?

My use case is that I have an `AsyncIterableIterator` of `Response` that I want to combine then all into one zip file. However, it seems to me that `client-zip` would need to write all data in the first input `Response` before starting the next one, which seems to align with what you said about "The ZIP output can only be created sequentially".

Given that we know the size of all inputs beforehand, can `client-zip` read all inputs in parallell and write to the right offset of the output?

**Comment by Touffy** [comment]
You are correct, all the data in the first Response needs to be copied before client-zip moves on to the next. What [DownloadStream](https://github.com/Touffy/dl-stream) achieves by starting several requests at a time is to nearly erase the effect of network latency and other kinds of overhead (authentication, server-side stuff…) that occur between calling `fetch` and resolving the Response. We're still limited by the data transfer capacity of the network and local filesystem, and the server's capacity to send the response body (and the first two do not scale).

As I've shown (in a test case without even any network lag or server processing), fetching multiple Responses that way can lead to significant improvements, up to 100% in my case, and it could be more if you have some real lag and very small files.

In theory, yes, what you ask could be done. Provided with the necessary metadata (the same that is required for the `predictLength` function), it's possible to generate the archive part for any file in the archive and to know exactly where to put it.

However, I don't see how it would help.

You see, when client-zip is running, the JavaScript interpreter is very busy copying the current file and computing its CRC32. Asking it to process another file concurrently would provide no benefit (and instead, very likely would degrade performance) unless the back-end is sending the data very slowly for each file but can scale to send multiple files at the same time.

So that leaves using Workers to process multiple files in parallel. In that case, each worker (assuming a host with multiple free CPU cores) can deal with a file without hurting the others. In theory…

Now, if we had a proper, seekable, OS filesystem handle with the capacity to let multiple Workers write to the same file at different positions without locking each other and without allocating the whole memory in the interpreter, the theory could work quite well in some cases (where the bottleneck is client-zip's CPU usage).

But in the browser, we don't have that. Even the Filesystem API (which is still half-experimental) does not allow that. We have SharedArrayBuffers which might support unsynchronised writing from multiple Workers, but that would require allocating the whole file's worth of bytes : not very practical since the performance gain would only be positive for large files in large archives (keep in mind that Workers are expensive to start up and talk to).

We also have Streams that multiple Workers could write to, but that requires synchronisation. There is no seeking in a stream. Communication between Workers is slow, and when it's not yet a Worker's turn to write, the only thing it can do is start computing CRC32 while using more and more memory.

**Comment by sntran** [comment]
Thanks for the detailed explanation! It makes sense and does not make sense to try to write in parallel due to locking and all the performance issues that come with it.

Rather, your `DownloadStream` gave me some inspirations. While I already did something similar fetching all my responses, it seems that I can do the same when writing data, by buffering the response's body into queue similar to `DownloadStream`, and it sped up the process quite a bit, depending on memory I suppose.
