### ISSUE TITLE
[BUG] Blob is not defined error in SvelteKit project

### ISSUE THREAD

**Issue by keanesnow98** [Touffy/client-zip#72]
Hi, I have seen the documentation for this awesome module.
I am running my SvelteKit project.
I have included downloadZip in my +page.ts file.
But then, if I run it, I got `Blob is not defined` error.
Please help!

**Comment by Touffy** [comment]
Hi.

First of all, if your version of Node.js hasn't heard of Blobs, you really should upgrade to at least Node 18 because [anything lower is already or very soon expired](https://github.com/nodejs/release#release-schedule).

But the point isn't to run client-zip in Node at all. In most cases, client-zip should only run in the bowser. [The SvelteKit docs](https://kit.svelte.dev/docs/load) say :

> A `load` function in a `+page.js` file runs both on the server and in the browser
> (unless combined with `export const ssr = false`, in which case it will [only run in the browser](https://kit.svelte.dev/docs/page-options#ssr))

Isolate the component which needs to call downloadZip, and mark it as browser-only.

**Comment by Touffy** [comment]
(this is similar to #28 although the workaround is simpler with SvelteKit ; did you actually read the documentation all the way to [Known Issues](https://github.com/Touffy/client-zip#Known-Issues) ?)
